# Generated by Django 6.0.6 on 2026-06-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('localizacao', models.CharField(blank=True, max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('catamara', 'Catamarã'), ('lancha', 'Lancha'), ('voadeira', 'Voadeira'), ('ecoturismo', 'Ecoturismo'), ('aventura', 'Aventura')], max_length=20)),
                ('tipo_valor', models.CharField(choices=[('fixo', 'Valor Fixo'), ('consultar', 'A Consultar')], default='fixo', max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ponto_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passeios.pontoturistico')),
            ],
        ),
    ]
