# Generated by Django 6.0.6 on 2026-06-06 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passeios', '0001_initial'),
        ('usuarios', '0002_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('horario_reserva', models.TimeField()),
                ('quantidade_turistas', models.IntegerField()),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cliente')),
                ('guia_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('guias_apoio', models.ManyToManyField(blank=True, related_name='reservas_apoio', to=settings.AUTH_USER_MODEL)),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passeios.passeio')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='reservas.reserva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
