# Generated by Django 6.0.6 on 2026-06-08 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
