# Generated by Django 6.0.6 on 2026-06-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='desativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
